- name: Generate private key
  command: openssl genrsa -out {{ key_location }} 2048 creates={{ key_location }}

- name: Generate CSR
  command: openssl req -new -subj {{ cert_fields }} -key {{ key_location }} -out {{ csr_location }} creates={{ csr_location }}

- name: Generate self-signed certificate
  command: openssl x509 -req -days 365 -in {{ csr_location }} -signkey {{ key_location }} -out {{ cert_location }} creates={{ cert_location }}
