- name: Retrieve certs from keystore using keytool
  shell: ./keytool -list -keystore ../jre/lib/security/cacerts -storepass changeit
  args:
    chdir: "/opt/java/current/bin"
  register: cert

# - debug:
#     msg: "{{ cert.stdout }}"
